# Generated by Django 5.2.7 on 2026-05-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='ISO 4217 currency code (e.g., IDR, SGD, EUR)', max_length=3, unique=True)),
                ('rate_to_usd', models.DecimalField(decimal_places=10, help_text='1 unit of this currency = X USD (e.g., 1 IDR = 0.000061 USD)', max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['currency_code'],
            },
        ),
    ]
