# Generated by Django 5.2.7 on 2025-10-17 09:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Latitude coordinate (-90 to 90)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Longitude coordinate (-180 to 180)",
                        max_digits=11,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "google_place_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Places API Place ID",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "price_range",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "$"), (2, "$$"), (3, "$$$"), (4, "$$$$")],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("total_visits", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("total_reviews", models.IntegerField(default=0)),
                (
                    "average_wfc_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average WFC rating (1-5)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as closed if cafe is no longer operating",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified by multiple users or admin"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cafes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cafe",
                "verbose_name_plural": "Cafes",
                "db_table": "cafes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="cafes.cafe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "db_table": "favorites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cafe",
            index=models.Index(
                fields=["latitude", "longitude"], name="cafes_latitud_92b599_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cafe",
            index=models.Index(
                fields=["google_place_id"], name="cafes_google__5c73ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cafe",
            index=models.Index(
                fields=["-average_wfc_rating"], name="cafes_average_6121cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "cafe")},
        ),
    ]
