# Generated by Django 5.2.7 on 2025-11-24 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CafeFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("not_cafe", "Not a cafe"),
                            ("wrong_location", "Wrong location"),
                            ("permanently_closed", "Permanently closed"),
                            ("duplicate", "Duplicate entry"),
                        ],
                        help_text="Reason for flagging this cafe",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional additional details about the issue",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        help_text="Current status of this flag",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on how this was resolved"
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="cafes.cafe",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who resolved this flag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_cafe_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafe_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cafe Flag",
                "verbose_name_plural": "Cafe Flags",
                "db_table": "cafe_flags",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="cafe_flags_status_b6e23b_idx",
                    ),
                    models.Index(
                        fields=["cafe", "status"], name="cafe_flags_cafe_id_4819d9_idx"
                    ),
                ],
                "unique_together": {("user", "cafe", "reason")},
            },
        ),
    ]
