# Generated by Django 5.2.7 on 2025-11-26 06:15

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0002_cafeflag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Geographic point (automatically synced from lat/lon)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddIndex(
            model_name="cafe",
            index=models.Index(fields=["location"], name="cafes_location_gist_idx"),
        ),
    ]
