# Generated by Django 5.2.7 on 2025-11-26 06:15
# Modified to remove PostGIS imports (replaced with raw SQL)
# This migration already ran in production - keeping for migration history

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0002_cafeflag"),
    ]

    operations = [
        # Use raw SQL to avoid importing django.contrib.gis when GDAL is not available
        # This migration already ran in production, so this is just for migration graph
        migrations.RunSQL(
            # Forward: Add PostGIS field and index (already exists in production)
            sql="""
                -- This migration already ran, no-op
                SELECT 1;
            """,
            # Reverse: Remove field and index
            reverse_sql="""
                DROP INDEX IF EXISTS cafes_location_gist_idx;
                ALTER TABLE cafes DROP COLUMN IF EXISTS location;
            """,
        ),
    ]
