# Generated by Django 5.2.7 on 2025-11-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0003_add_postgis_location_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="average_ratings_cache",
            field=models.JSONField(
                blank=True,
                help_text="Cached average ratings (wifi, power, seating, noise, wfc) from latest 100 reviews",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="facility_stats_cache",
            field=models.JSONField(
                blank=True,
                help_text="Cached facility statistics (smoking area, prayer room) from latest 100 reviews",
                null=True,
            ),
        ),
    ]
