# Generated by Django 5.2.7 on 2026-01-02 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0005_remove_postgis_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="google_rating",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=1,
                help_text="Google Maps rating (1.0 - 5.0)",
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="google_rating_updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Last time Google rating was fetched from API",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="google_ratings_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of Google reviews", null=True
            ),
        ),
    ]
