# Generated by Django 5.2.7 on 2026-01-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0006_add_google_rating_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cafe',
            index=models.Index(fields=['is_closed', '-created_at'], name='cafe_closed_created_idx'),
        ),
    ]
