# Generated by Django 5.2.7 on 2026-01-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0007_add_is_closed_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'cafe'], name='favorite_lookup_idx'),
        ),
    ]
