# Generated by Django 5.2.7 on 2026-05-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0012_populate_filter_columns'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cafelist',
            new_name='cafe_lists_owner_i_9155d7_idx',
            old_name='cafelist_owner_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='cafelist',
            new_name='cafe_lists_owner_i_a7aefe_idx',
            old_name='cafelist_owner_default_idx',
        ),
        migrations.RenameIndex(
            model_name='cafelistitem',
            new_name='cafe_list_i_cafe_li_817e16_idx',
            old_name='cafelistitem_list_added_idx',
        ),
        migrations.RenameIndex(
            model_name='cafelistitem',
            new_name='cafe_list_i_cafe_id_5eef4f_idx',
            old_name='cafelistitem_cafe_list_idx',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='facility_stats_cache',
            field=models.JSONField(blank=True, help_text='Cached facility mention counts (smoking area, prayer room, indoor/outdoor seating) from latest 100 reviews', null=True),
        ),
    ]
