# Generated by Django 5.2.7 on 2026-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0013_rename_cafelist_owner_updated_idx_cafe_lists_owner_i_9155d7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='insights_cache',
            field=models.JSONField(blank=True, help_text='Computed cafe insights (median spend, time-of-day distribution, best-for labels, recency). Recomputed on visit/review writes and nightly for time-decaying fields.', null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='insights_cache_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='insights_cache_version',
            field=models.IntegerField(default=1, help_text='Schema version of insights_cache. Bump to invalidate on logic changes.'),
        ),
    ]
