# Generated by Django 5.2.7 on 2026-05-06 04:33

from django.conf import settings
from django.db import migrations, models


def set_list_types_for_existing_lists(apps, schema_editor):
    """Set list_type='favorites' for existing default lists, 'custom' for others."""
    CafeList = apps.get_model('cafes', 'CafeList')
    CafeList.objects.filter(is_default=True).update(list_type='favorites', icon='heart')
    CafeList.objects.filter(list_type='custom', is_default=False).update(icon='bookmark')


def create_to_go_lists_for_existing_users(apps, schema_editor):
    """Create a 'to-go' list for every user who doesn't have one yet."""
    CafeList = apps.get_model('cafes', 'CafeList')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    for user in User.objects.all():
        has_to_go = CafeList.objects.filter(owner=user, list_type='to_go').exists()
        if has_to_go:
            continue

        base_name = 'to-go'
        name = base_name
        counter = 1
        while CafeList.objects.filter(owner=user, name=name).exists():
            name = f"{base_name} ({counter})"
            counter += 1

        CafeList.objects.create(
            owner=user,
            name=name,
            list_type='to_go',
            icon='bookmark',
            is_default=True,
        )


def reverse_migration(apps, schema_editor):
    """Reverse: delete all to-go lists, reset list_type to custom."""
    CafeList = apps.get_model('cafes', 'CafeList')
    CafeList.objects.filter(list_type='to_go').delete()
    CafeList.objects.filter(list_type='favorites').update(list_type='custom', icon='bookmark')


class Migration(migrations.Migration):
    # Non-atomic: each operation runs in its own transaction.
    # This avoids PostgreSQL "pending trigger events" errors when
    # schema changes follow data changes.
    atomic = False

    dependencies = [
        ('cafes', '0016_pricecluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cafelist',
            name='unique_default_list_per_user',
        ),
        migrations.RemoveIndex(
            model_name='cafelist',
            name='cafe_lists_owner_i_a7aefe_idx',
        ),
        migrations.AddField(
            model_name='cafelist',
            name='icon',
            field=models.CharField(choices=[('bookmark', 'Bookmark'), ('heart', 'Heart'), ('coffee', 'Coffee'), ('wifi', 'WiFi'), ('star', 'Star'), ('map-pin', 'Map Pin'), ('briefcase', 'Briefcase'), ('users', 'Users'), ('moon', 'Moon'), ('sun', 'Sun'), ('music', 'Music'), ('book-open', 'Book Open'), ('camera', 'Camera'), ('gift', 'Gift'), ('home', 'Home'), ('plane', 'Plane'), ('zap', 'Zap')], default='bookmark', help_text='Lucide icon name for this list.', max_length=30),
        ),
        migrations.AddField(
            model_name='cafelist',
            name='list_type',
            field=models.CharField(choices=[('to_go', 'to-go'), ('favorites', 'favorites'), ('custom', 'Custom')], default='custom', help_text='Special lists (to-go, favorites) are protected and auto-created.', max_length=20),
        ),
        migrations.AlterField(
            model_name='cafelist',
            name='is_default',
            field=models.BooleanField(default=False, help_text='True for to-go and favorites (protected special lists).'),
        ),
        migrations.AddIndex(
            model_name='cafelist',
            index=models.Index(fields=['owner', 'list_type'], name='cafe_lists_owner_i_154683_idx'),
        ),
        migrations.AddConstraint(
            model_name='cafelist',
            constraint=models.UniqueConstraint(condition=models.Q(('list_type', 'custom'), _negated=True), fields=('owner', 'list_type'), name='unique_special_list_per_user'),
        ),
        migrations.RunPython(set_list_types_for_existing_lists, reverse_code=reverse_migration),
        migrations.RunPython(create_to_go_lists_for_existing_users, reverse_code=migrations.RunPython.noop),
    ]
