# Generated by Django 5.2.7 on 2026-05-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0019_align_cafelist_description_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafelist',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Appears on the Discover panel when also is_featured=True.'),
        ),
    ]
