# Generated by Django 5.2.7 on 2026-05-12 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0020_alter_cafelist_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cafelist',
            name='save_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Denormalized count; updated via signal on save/unsave.'),
        ),
        migrations.CreateModel(
            name='SavedCafeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('cafe_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='cafes.cafelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cafe_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_cafe_lists',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['cafe_list', '-saved_at'], name='saved_cafe__cafe_li_afc1a0_idx'), models.Index(fields=['user', '-saved_at'], name='saved_cafe__user_id_f54d80_idx')],
                'unique_together': {('user', 'cafe_list')},
            },
        ),
    ]
