# Generated by Django 5.2.7 on 2026-05-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0021_savedcafelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafelist',
            name='share_token',
            field=models.UUIDField(blank=True, help_text="Auto-generated when visibility='shareable'. Used for shareable link access.", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cafelist',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shareable', 'Shareable'), ('public', 'Public')], db_index=True, default='private', help_text='Who can view this list. Private=owner only, Shareable=anyone with link, Public=everyone.', max_length=10),
        ),
        migrations.AlterField(
            model_name='cafelist',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text="Featured lists appear on the Discover panel. Requires visibility='public'."),
        ),
        migrations.AlterField(
            model_name='cafelist',
            name='is_public',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use visibility field instead.'),
        ),
    ]
