# Generated by Django 5.2.7 on 2025-12-07 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public - Anyone can view"),
                            ("private", "Private - Only me"),
                        ],
                        default="public",
                        help_text="Who can view your profile",
                        max_length=20,
                    ),
                ),
                (
                    "show_activity_dates",
                    models.BooleanField(
                        default=True,
                        help_text="Show dates on your activity (reviews and visits)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
                "db_table": "user_settings",
            },
        ),
    ]
