# Generated by Django 5.2.7 on 2025-12-22 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="following_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="activity_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public - Everyone"),
                    ("followers", "Followers Only"),
                    ("private", "Private - Only Me"),
                ],
                default="public",
                help_text="Who can see your activity in their feed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="show_followers",
            field=models.BooleanField(default=True, help_text="Show who follows you"),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="show_following",
            field=models.BooleanField(default=True, help_text="Show who you follow"),
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed",
                    models.ForeignKey(
                        help_text="User being followed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        help_text="User who is following",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow",
                "verbose_name_plural": "Follows",
                "db_table": "follows",
                "indexes": [
                    models.Index(
                        fields=["follower", "-created_at"],
                        name="follows_followe_2ac7b3_idx",
                    ),
                    models.Index(
                        fields=["followed", "-created_at"],
                        name="follows_followe_d271db_idx",
                    ),
                ],
                "unique_together": {("follower", "followed")},
            },
        ),
    ]
