# Generated by Django 5.2.7 on 2025-12-24 10:34

from django.db import migrations


def drop_unused_postgres_tables(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    statements = [
        "DROP EXTENSION IF EXISTS postgis CASCADE;",
        "DROP TABLE IF EXISTS authtoken_token CASCADE;",
        "DROP TABLE IF EXISTS account_emailconfirmation CASCADE;",
        "DROP TABLE IF EXISTS account_emailaddress CASCADE;",
    ]
    for statement in statements:
        schema_editor.execute(statement)


class Migration(migrations.Migration):
    """
    Drop unused database tables to clean up the database.

    Tables being dropped:
    1. spatial_ref_sys - PostGIS legacy (7.1 MB) - no longer using PostGIS
    2. authtoken_token - DRF token auth (using JWT instead)
    3. account_emailaddress - Email verification (not enforced)
    4. account_emailconfirmation - Email verification tokens (not enforced)
    """

    dependencies = [
        ("accounts", "0003_add_social_features"),
    ]

    operations = [
        migrations.RunPython(
            drop_unused_postgres_tables,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
