# Generated by Django 5.2.7 on 2025-12-24 10:34

from django.db import migrations


class Migration(migrations.Migration):
    """
    Drop unused database tables to clean up the database.

    Tables being dropped:
    1. spatial_ref_sys - PostGIS legacy (7.1 MB) - no longer using PostGIS
    2. authtoken_token - DRF token auth (using JWT instead)
    3. account_emailaddress - Email verification (not enforced)
    4. account_emailconfirmation - Email verification tokens (not enforced)
    """

    dependencies = [
        ("accounts", "0003_add_social_features"),
    ]

    operations = [
        # Drop PostGIS extension (which will automatically drop spatial_ref_sys table - 7.1 MB!)
        migrations.RunSQL(
            sql="DROP EXTENSION IF EXISTS postgis CASCADE;",
            reverse_sql="-- Cannot reverse: PostGIS extension"
        ),

        # Drop DRF token authentication (using JWT instead)
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS authtoken_token CASCADE;",
            reverse_sql="-- Cannot reverse: DRF authtoken table"
        ),

        # Drop email verification tables (not enforcing email verification)
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS account_emailconfirmation CASCADE;",
            reverse_sql="-- Cannot reverse: django-allauth table"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS account_emailaddress CASCADE;",
            reverse_sql="-- Cannot reverse: django-allauth table"
        ),
    ]
