# Generated by Django 5.2.7 on 2026-01-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_email_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Custom display name. If not set, username is used.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last username change, for cooldown tracking",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_anonymous_display",
            field=models.BooleanField(
                default=False,
                help_text="If True, username/display_name will be displayed as masked (e.g., 'joh***')",
            ),
        ),
    ]
