# Generated by Django 5.2.7 on 2026-04-09 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_display_name_user_username_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_only',
            field=models.BooleanField(default=False, help_text='True if user was created via OAuth and never had a password'),
        ),
        migrations.CreateModel(
            name='LinkedProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('twitter', 'Twitter')], max_length=20)),
                ('provider_user_id', models.CharField(help_text='External user ID from OAuth provider (Google sub, Twitter user ID)', max_length=255)),
                ('email', models.EmailField(db_index=True, help_text='Email from OAuth provider, used for account linking', max_length=254)),
                ('display_name', models.CharField(blank=True, default='', help_text='Username/handle from OAuth provider (Twitter @handle, etc.)', max_length=255)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'linked_providers',
                'indexes': [models.Index(fields=['user', 'provider'], name='lp_user_provider_idx'), models.Index(fields=['email'], name='lp_email_idx')],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
