# Generated by Django 5.2.7 on 2026-04-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_oauth_only_linkedprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oauth_only',
        ),
        migrations.AlterField(
            model_name='linkedprovider',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Username/handle from OAuth provider', max_length=255),
        ),
        migrations.AlterField(
            model_name='linkedprovider',
            name='provider_user_id',
            field=models.CharField(help_text='External user ID from OAuth provider (e.g. Google sub)', max_length=255),
        ),
    ]
