# Generated by Django 5.2.7 on 2026-05-13 05:19

from django.db import migrations, models


def migrate_is_anonymous_display(apps, schema_editor):
    """
    For users with is_anonymous_display=True, set profile_visibility to 'private'.
    is_anonymous_display is being merged into profile_visibility.
    """
    User = apps.get_model('accounts', 'User')
    UserSettings = apps.get_model('accounts', 'UserSettings')
    
    for user in User.objects.filter(is_anonymous_display=True).iterator():
        settings, _ = UserSettings.objects.get_or_create(user=user)
        if settings.profile_visibility == 'public':
            settings.profile_visibility = 'private'
            settings.save(update_fields=['profile_visibility'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_oauth_only_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='active', help_text='Follow relationship status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed', 'status'], name='follows_followed_status_idx'),
        ),
        migrations.RunPython(
            migrate_is_anonymous_display,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_anonymous_display',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_anonymous_display',
        ),
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='active', help_text='Follow relationship status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed', 'status'], name='follows_followed_status_idx'),
        ),
    ]
