# Generated by hand after adding the follows_follower_status_idx index.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_anonymous_display_add_follow_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'status'], name='follows_follower_status_idx'),
        ),
    ]
