# Generated by OpenCode on 2026-05-16

from django.db import migrations


def remove_activity_content_type(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(app_label='activity').delete()


def drop_activity_table(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TABLE IF EXISTS activities CASCADE;')
    else:
        schema_editor.execute('DROP TABLE IF EXISTS activities;')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_follower_status_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='activity_visibility',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_activity_dates',
        ),
        migrations.RunPython(
            drop_activity_table,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            remove_activity_content_type,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
