# Generated by Django 5.2.7 on 2025-12-24 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("visit", "Visit"),
                            ("review", "Review"),
                            ("follow", "Follow"),
                        ],
                        db_index=True,
                        help_text="Type of activity",
                        max_length=20,
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of target object", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Denormalized data: cafe_name, rating, comment, actor info, etc.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the activity occurred",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who sees this activity in their feed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_feed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of target object (Visit, Review, Follow)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"], name="feed_query_idx"
                    ),
                    models.Index(
                        fields=["recipient", "activity_type", "-created_at"],
                        name="feed_type_idx",
                    ),
                    models.Index(
                        fields=["is_deleted", "created_at"], name="cleanup_idx"
                    ),
                ],
            },
        ),
    ]
