# Generated by Django 5.2.7 on 2026-01-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_create_activity_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("visit", "Visit (DEPRECATED - privacy fix)"),
                    ("review", "Review"),
                    ("follow", "Follow"),
                ],
                db_index=True,
                help_text="Type of activity",
                max_length=20,
            ),
        ),
    ]
