# Generated by Django 5.2.7 on 2026-04-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('review', 'Review'), ('follow', 'Follow')], db_index=True, help_text='Type of activity', max_length=20),
        ),
    ]
