import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import GoogleLoginButton from '../components/auth/GoogleLoginButton';
import UsernameSetupModal from '../components/auth/UsernameSetupModal';
import LegacyUserMigrationModal from '../components/auth/LegacyUserMigrationModal';
import { trackUserSignedUp, trackUserLoggedIn, trackUsernameSetupCompleted } from '../lib/analytics';
import { User } from '../types';

const AuthPage: React.FC = () => {
  const { user, loading, login, checkMigrationStatus } = useAuth();
  const navigate = useNavigate();
  const didCheckAuth = useRef(false);
  const [showUsernameSetup, setShowUsernameSetup] = useState(false);
  const [showMigrationModal, setShowMigrationModal] = useState(false);
  const [newUser, setNewUser] = useState<User | null>(null);

  // Check authentication and migration status on mount
  useEffect(() => {
    const checkAuthAndMigration = async () => {
      if (!loading && !didCheckAuth.current) {
        didCheckAuth.current = true;

        if (user) {
          // User is logged in, check if they need migration
          try {
            const migrationStatus = await checkMigrationStatus();
            if (migrationStatus.needs_migration) {
              // Legacy user needs to link OAuth
              setShowMigrationModal(true);
              return;
            }
            // User is fully authenticated, redirect to map
            navigate('/map', { replace: true });
          } catch (error) {
            // If we can't check migration status, just redirect to map
            navigate('/map', { replace: true });
          }
        }
      }
    };

    checkAuthAndMigration();
  }, [user, loading, navigate, checkMigrationStatus]);

  const handleOAuthSuccess = async (
    provider: 'google',
    result: { user: User; created: boolean }
  ) => {
    const { user: userData, created } = result;

    // Track analytics event
    if (created) {
      trackUserSignedUp(provider);
    } else {
      trackUserLoggedIn(provider);
    }

    // Check if this is a new user with auto-generated username
    const hasAutoGeneratedUsername = /\d+$/.test(userData.username);

    if (hasAutoGeneratedUsername && created) {
      // Show username setup modal for new users
      setNewUser(userData);
      setShowUsernameSetup(true);
    } else {
      // Existing user or user without auto-generated username - go to map
      navigate('/map');
    }
  };

  const handleUsernameSetupComplete = (newUsername: string, skipped: boolean) => {
    setShowUsernameSetup(false);

    // Track username setup completion
    trackUsernameSetupCompleted({ action: skipped ? 'skipped' : 'set_username' });

    // Update user in context with new username
    if (newUser) {
      login('google', ''); // Refresh the auth context
    }

    // Navigate to map
    navigate('/map');
  };

  const handleMigrationComplete = () => {
    setShowMigrationModal(false);
    navigate('/map');
  };

  return (
    <div className="auth-page">
      <div className="auth-card">
        <div className="logo">
          <h1>Can-It-WFC</h1>
          <p>Work from cafe reviews</p>
        </div>

        <div className="auth-buttons">
          <GoogleLoginButton mode="signin" onSuccess={handleOAuthSuccess} />
        </div>

        <div className="info-text">
          <p>Sign in to save cafes, leave reviews, and more!</p>
        </div>
      </div>

      {newUser && (
        <UsernameSetupModal
          isOpen={showUsernameSetup}
          currentUsername={newUser.username}
          email={newUser.email}
          onComplete={handleUsernameSetupComplete}
        />
      )}

      {user && (
        <LegacyUserMigrationModal
          isOpen={showMigrationModal}
          onComplete={handleMigrationComplete}
        />
      )}

      <style>{`
        .auth-page {
          min-height: 100vh;
          display: flex;
          align-items: center;
          justify-content: center;
          background: var(--neo-primary);
          padding: 20px;
        }

        .auth-card {
          background: var(--neo-white);
          border: var(--neo-border-width-thick) solid var(--neo-black);
          border-radius: var(--neo-border-radius);
          padding: 40px;
          width: 100%;
          max-width: 420px;
          box-shadow: var(--neo-shadow-offset-lg) var(--neo-shadow-offset-lg) 0 var(--neo-black);
        }

        .logo {
          text-align: center;
          margin-bottom: 32px;
        }

        .logo h1 {
          font-size: 36px;
          font-weight: var(--neo-font-black);
          color: var(--neo-black);
          margin: 0 0 8px 0;
          text-transform: uppercase;
          letter-spacing: 1px;
        }

        .logo p {
          font-size: 14px;
          color: var(--neo-gray-600);
          margin: 0;
          font-weight: var(--neo-font-bold);
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }

        .auth-buttons {
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .info-text {
          text-align: center;
          margin-top: 24px;
          padding-top: 24px;
          border-top: var(--neo-border-width-thin) solid var(--neo-gray-200);
        }

        .info-text p {
          margin: 0;
          font-size: 14px;
          color: var(--neo-gray-600);
          font-weight: 500;
        }

        @media (max-width: 480px) {
          .auth-card {
            padding: 32px 24px;
          }

          .logo h1 {
            font-size: 28px;
          }
        }
      `}</style>
    </div>
  );
};

export default AuthPage;
