import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import GoogleLoginButton from '../components/auth/GoogleLoginButton';
import UsernameSetupModal from '../components/auth/UsernameSetupModal';
import LegacyUserMigrationModal from '../components/auth/LegacyUserMigrationModal';
import { trackUserSignedUp, trackUserLoggedIn, trackUsernameSetupCompleted } from '../lib/analytics';
import { User } from '../types';
import styles from './LandingPage.module.css';

/**
 * Landing Page — Minimal Neobrutalist Login
 * Centered card with Google OAuth only.
 */
const LandingPage: React.FC = () => {
  const navigate = useNavigate();
  const { user, loading, checkMigrationStatus } = useAuth();
  const didCheckAuth = useRef(false);
  const [showUsernameSetup, setShowUsernameSetup] = useState(false);
  const [showMigrationModal, setShowMigrationModal] = useState(false);
  const [newUser, setNewUser] = useState<User | null>(null);

  useEffect(() => {
    const checkAuthAndMigration = async () => {
      if (!loading && !didCheckAuth.current) {
        didCheckAuth.current = true;
        if (user) {
          try {
            const migrationStatus = await checkMigrationStatus();
            if (migrationStatus.needs_migration) {
              setShowMigrationModal(true);
              return;
            }
          } catch {}
          navigate('/map', { replace: true });
        }
      }
    };
    checkAuthAndMigration();
  }, [user, loading, navigate, checkMigrationStatus]);

  const handleOAuthSuccess = async (
    provider: 'google',
    result: { user: User; created: boolean }
  ) => {
    const { user: userData, created } = result;
    if (created) {
      trackUserSignedUp(provider);
    } else {
      trackUserLoggedIn(provider);
    }
    const hasAutoGeneratedUsername = /\d+$/.test(userData.username);
    if (hasAutoGeneratedUsername && created) {
      setNewUser(userData);
      setShowUsernameSetup(true);
    } else {
      navigate('/map');
    }
  };

  const handleUsernameSetupComplete = (_newUsername: string, skipped: boolean) => {
    setShowUsernameSetup(false);
    trackUsernameSetupCompleted({ action: skipped ? 'skipped' : 'set_username' });
    navigate('/map');
  };

  const handleMigrationComplete = () => {
    setShowMigrationModal(false);
    navigate('/map');
  };

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <div className={styles.logoSection}>
          <div className={styles.cupContainer} aria-hidden="true">
            <div className={styles.cup} />
            <div className={styles.handle} />
            <div className={`${styles.steam} ${styles.steam1}`} />
            <div className={`${styles.steam} ${styles.steam2}`} />
            <div className={`${styles.steam} ${styles.steam3}`} />
          </div>
          <h1 className={styles.logo}>CAN-IT-WFC</h1>
          <div className={styles.logoUnderline} />
          <p className={styles.tagline}>Find cafes worth working from</p>
        </div>

        <hr className={styles.divider} />

        <div className={styles.loginSection}>
          <GoogleLoginButton
            mode="signin"
            variant="default"
            onSuccess={handleOAuthSuccess}
          />
        </div>
      </div>

      <footer className={styles.footer}>
        <span>© {new Date().getFullYear()} Can-It-WFC</span>
      </footer>

      {newUser && (
        <UsernameSetupModal
          isOpen={showUsernameSetup}
          currentUsername={newUser.username}
          email={newUser.email}
          onComplete={handleUsernameSetupComplete}
        />
      )}
      {user && (
        <LegacyUserMigrationModal
          isOpen={showMigrationModal}
          onComplete={handleMigrationComplete}
        />
      )}
    </div>
  );
};

export default LandingPage;
