import React, { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { trackUserSignedUp, trackUserLoggedIn } from '../lib/analytics';
import { extractApiError } from '../utils/errorUtils';
import { logger } from '../utils/logger';

const TwitterCallbackPage: React.FC = () => {

const TwitterCallbackPage: React.FC = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const [error, setError] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const handleTwitterCallback = async () => {
      const code = searchParams.get('code');
      const state = searchParams.get('state');
      const errorParam = searchParams.get('error');
      const codeVerifier = sessionStorage.getItem('twitter_code_verifier');
      const mode = sessionStorage.getItem('twitter_auth_mode') || 'signin';

      // Clear sessionStorage
      sessionStorage.removeItem('twitter_code_verifier');
      sessionStorage.removeItem('twitter_auth_mode');

      // Handle errors from Twitter
      if (errorParam) {
        setError(`Twitter authorization failed: ${errorParam}`);
        setLoading(false);
        setTimeout(() => navigate('/auth', { replace: true }), 3000);
        return;
      }

      // Validate required parameters
      if (!code || !state || !codeVerifier) {
        setError('Invalid Twitter callback. Missing required parameters.');
        setLoading(false);
        setTimeout(() => navigate('/auth', { replace: true }), 3000);
        return;
      }

      try {
        // Exchange auth code for access token via backend proxy
        // The backend will handle the token exchange with Twitter
        const redirectUri = `${window.location.origin}/auth/twitter/callback`;

        // Call our backend endpoint to exchange the code
        const response = await fetch('/api/auth/twitter/callback/', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          credentials: 'include',
          body: JSON.stringify({
            code,
            code_verifier: state, // state contains the code_verifier
            redirect_uri: redirectUri,
          }),
        });

        if (!response.ok) {
          const errorData = await response.json().catch(() => ({}));
          throw new Error(errorData.detail || 'Twitter authentication failed');
        }

        const data = await response.json();
        const { user, created } = data;

        // Update auth context with user data
        const authMethod = 'twitter' as const;

        // Identify in analytics
        if (created) {
          trackUserSignedUp(authMethod);
        } else {
          trackUserLoggedIn(authMethod);
        }

        // Store result for AuthPage to pick up
        sessionStorage.setItem('twitter_oauth_result', JSON.stringify({ user, created }));

        // Navigate to map or username setup
        const hasAutoGeneratedUsername = /\d+$/.test(user.username);
        if (hasAutoGeneratedUsername && created) {
          // New user with auto-generated username - go to map
          // (Username setup modal will be shown by AuthPage on next visit)
          navigate('/map', { replace: true });
        } else {
          // Existing user - go to map
          navigate('/map', { replace: true });
        }
      } catch (err) {
        logger.error('Twitter callback error', err as Error, 'TwitterCallbackPage');
        const apiError = extractApiError(err);
        setError(apiError.message || 'Failed to authenticate with Twitter. Please try again.');
        setLoading(false);
        setTimeout(() => navigate('/auth', { replace: true }), 3000);
      }
    };

    handleTwitterCallback();
  }, [searchParams, navigate]);

  if (loading) {
    return (
      <div style={styles.page}>
        <div style={styles.card}>
          <div style={styles.spinner}></div>
          <p style={styles.text}>Signing in with Twitter...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div style={styles.page}>
        <div style={styles.card}>
          <div style={styles.errorIcon}>⚠️</div>
          <h2 style={styles.errorTitle}>Authentication Failed</h2>
          <p style={styles.errorMessage}>{error}</p>
          <p style={styles.redirectText}>Redirecting to sign in page...</p>
        </div>
      </div>
    );
  }

  return null;
};

const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--neo-primary)',
    padding: '20px',
  } as React.CSSProperties,
  card: {
    background: 'var(--neo-white)',
    border: '3px solid var(--neo-black)',
    borderRadius: '12px',
    padding: '40px',
    width: '100%',
    maxWidth: '400px',
    textAlign: 'center' as const,
    boxShadow: '6px 6px 0 var(--neo-black)',
  },
  spinner: {
    width: '48px',
    height: '48px',
    margin: '0 auto 20px',
    border: '4px solid var(--neo-gray-200)',
    borderTopColor: 'var(--neo-primary)',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  text: {
    margin: 0,
    fontSize: '16px',
    fontWeight: '500',
    color: 'var(--neo-black)',
  },
  errorIcon: {
    fontSize: '48px',
    marginBottom: '16px',
  },
  errorTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    margin: '0 0 12px 0',
    color: 'var(--neo-black)',
  },
  errorMessage: {
    fontSize: '14px',
    margin: '0 0 20px 0',
    color: 'var(--neo-danger)',
  },
  redirectText: {
    fontSize: '14px',
    margin: 0,
    color: 'var(--neo-gray-600)',
  },
};

export default TwitterCallbackPage;
