import React, { useState } from 'react';
import { GoogleOAuthProvider, GoogleLogin, CredentialResponse } from '@react-oauth/google';
import { authApi } from '../../api/client';
import { useAuth } from '../../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { useResultModal } from '../../hooks';
import { ResultModal } from '../common';
import UsernameSetupModal from './UsernameSetupModal';
import { User } from '../../types';
import styles from './GoogleLoginButton.module.css';

const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_OAUTH_CLIENT_ID || '';

interface GoogleLoginButtonProps {
  mode?: 'signin' | 'signup';
}

const GoogleLoginButtonInner: React.FC<GoogleLoginButtonProps> = ({ mode = 'signin' }) => {
  const { login, updateUser } = useAuth();
  const navigate = useNavigate();
  const resultModal = useResultModal();
  const [showUsernameSetup, setShowUsernameSetup] = useState(false);
  const [newUser, setNewUser] = useState<User | null>(null);

  const handleSuccess = async (credentialResponse: CredentialResponse) => {
    if (!credentialResponse.credential) {
      resultModal.showResultModal({
        type: 'error',
        title: 'Google Sign-In Failed',
        message: 'No credential received from Google. Please try again.',
      });
      return;
    }

    try {
      const { user, access, refresh } = await authApi.googleLogin(credentialResponse.credential);

      // Login with Google OAuth data (wrapped in object)
      await login({ user, access, refresh });

      // Check if this is a new user with auto-generated username (contains numbers at the end)
      const hasAutoGeneratedUsername = /\d+$/.test(user.username);

      if (hasAutoGeneratedUsername && mode === 'signup') {
        // Show username setup modal for new users
        setNewUser(user);
        setShowUsernameSetup(true);
        // DON'T navigate - let the modal handle navigation after completion
      } else {
        // Existing user or user chose to skip - go directly to map
        navigate('/map');
      }
    } catch (error: any) {
      if (import.meta.env.DEV) {
        console.error('Google login error:', error);
      }
      resultModal.showResultModal({
        type: 'error',
        title: 'Google Sign-In Failed',
        message: error.response?.data?.detail ||
                 error.response?.data?.non_field_errors?.[0] ||
                 'Failed to sign in with Google. Please try again.',
      });
    }
  };

  const handleUsernameSetupComplete = (newUsername: string) => {
    setShowUsernameSetup(false);

    // Update user in context with new username
    if (newUser) {
      updateUser({ ...newUser, username: newUsername });
    }

    // Navigate to map
    navigate('/map');
  };

  const handleError = () => {
    resultModal.showResultModal({
      type: 'error',
      title: 'Google Sign-In Failed',
      message: 'Failed to authenticate with Google. Please try again.',
    });
  };

  if (!GOOGLE_CLIENT_ID) {
    return (
      <div className={styles.error}>
        <p>Google Sign-In is not configured. Please contact support.</p>
      </div>
    );
  }

  return (
    <>
      <div className={styles.googleButton}>
        <GoogleLogin
          onSuccess={handleSuccess}
          onError={handleError}
          text={mode === 'signup' ? 'signup_with' : 'signin_with'}
          theme="outline"
          size="large"
          width="100%"
        />
      </div>

      {newUser && (
        <UsernameSetupModal
          isOpen={showUsernameSetup}
          currentUsername={newUser.username}
          email={newUser.email}
          onComplete={handleUsernameSetupComplete}
        />
      )}

      <ResultModal
        isOpen={resultModal.isOpen}
        onClose={resultModal.closeResultModal}
        type={resultModal.type}
        title={resultModal.title}
        message={resultModal.message}
        details={resultModal.details}
        primaryButton={resultModal.primaryButton}
        secondaryButton={resultModal.secondaryButton}
        autoClose={resultModal.autoClose}
        autoCloseDelay={resultModal.autoCloseDelay}
      />
    </>
  );
};

const GoogleLoginButton: React.FC<GoogleLoginButtonProps> = (props) => {
  if (!GOOGLE_CLIENT_ID) {
    return (
      <div style={{ padding: '12px', background: '#FEF3C7', border: '2px solid #000', borderRadius: '4px', marginBottom: '20px' }}>
        <p style={{ margin: 0, fontSize: '14px', fontWeight: 'bold' }}>
          ⚠️ Google Sign-In not configured. Add VITE_GOOGLE_OAUTH_CLIENT_ID to .env
        </p>
      </div>
    );
  }

  return (
    <GoogleOAuthProvider clientId={GOOGLE_CLIENT_ID}>
      <GoogleLoginButtonInner {...props} />
    </GoogleOAuthProvider>
  );
};

export default GoogleLoginButton;
