# Generated by Django 5.2.7 on 2025-10-17 09:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cafes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Date of the visit"
                    ),
                ),
                (
                    "check_in_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Latitude when checking in (for verification)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "check_in_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Longitude when checking in (for verification)",
                        max_digits=11,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="cafes.cafe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit",
                "verbose_name_plural": "Visits",
                "db_table": "visits",
                "ordering": ["-visit_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wifi_quality",
                    models.IntegerField(
                        help_text="WiFi quality (1=very poor, 5=excellent)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "power_outlets_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Accessibility/quantity of outlets (1=very few, 5=plenty)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "noise_level",
                    models.IntegerField(
                        help_text="Noise level (1=very quiet, 5=very loud)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "seating_comfort",
                    models.IntegerField(
                        help_text="Seating comfort (1=very uncomfortable, 5=very comfortable)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "space_availability",
                    models.IntegerField(
                        help_text="How crowded/available is space (1=always full, 5=plenty of space)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "coffee_quality",
                    models.IntegerField(
                        help_text="Coffee quality (1=very poor, 5=excellent)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "menu_options",
                    models.IntegerField(
                        help_text="Menu variety (1=very limited, 5=extensive)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "bathroom_quality",
                    models.IntegerField(
                        blank=True,
                        help_text="Bathroom quality (1=very poor, 5=excellent)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "wfc_rating",
                    models.IntegerField(
                        help_text="Overall WFC suitability (1=not suitable, 5=perfect for WFC)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "visit_time",
                    models.IntegerField(
                        choices=[
                            (1, "Morning (Open - 1pm)"),
                            (2, "Afternoon (1pm - 6pm)"),
                            (3, "Evening (6pm - Close)"),
                        ],
                        help_text="Time of visit",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional review (max 160 characters)",
                        max_length=160,
                    ),
                ),
                ("is_flagged", models.BooleanField(default=False)),
                ("flag_count", models.IntegerField(default=0)),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Hidden reviews are not shown publicly"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="cafes.cafe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        help_text="Link to a specific visit (required)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="reviews.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate content"),
                            ("fake", "Fake review"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flagged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Flag",
                "verbose_name_plural": "Review Flags",
                "db_table": "review_flags",
                "ordering": ["-created_at"],
                "unique_together": {("review", "flagged_by")},
            },
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["cafe", "-visit_date"], name="visits_cafe_id_afba2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["user", "-visit_date"], name="visits_user_id_cdc29b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visit",
            unique_together={("user", "cafe", "visit_date")},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["cafe", "-created_at"], name="reviews_cafe_id_373b20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "-created_at"], name="reviews_user_id_9f7b05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["-wfc_rating"], name="reviews_wfc_rat_0d2d56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["is_hidden"], name="reviews_is_hidd_91216e_idx"),
        ),
    ]
