# Generated by Django 5.2.7 on 2025-10-21 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="helpful_count",
            field=models.IntegerField(
                default=0, help_text="Number of users who found this review helpful"
            ),
        ),
        migrations.CreateModel(
            name="ReviewHelpful",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpful_marks",
                        to="reviews.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpful_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Helpful Mark",
                "verbose_name_plural": "Review Helpful Marks",
                "db_table": "review_helpful",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["review", "-created_at"],
                        name="review_help_review__cbfc3c_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="review_help_user_id_e86ffe_idx",
                    ),
                ],
                "unique_together": {("review", "user")},
            },
        ),
    ]
