# Generated by Django 5.2.7 on 2025-10-30 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_helpful_count_reviewhelpful"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="amount_spent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount spent in USD",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="visit_time",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Morning (6AM - 12PM)"),
                    (2, "Afternoon (12PM - 6PM)"),
                    (3, "Evening (6PM - 12AM)"),
                ],
                help_text="Time of day visited (1=Morning, 2=Afternoon, 3=Evening)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
