# Generated by Django 5.2.7 on 2025-11-01 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_visit_amount_spent_visit_visit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="visit_time",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Morning (Open - 1pm)"),
                    (2, "Afternoon (1pm - 6pm)"),
                    (3, "Evening (6pm - Close)"),
                ],
                help_text="Time of visit (deprecated - now stored in Visit model)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
