# Generated by Django 5.2.7 on 2025-11-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_alter_review_visit_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="has_prayer_room",
            field=models.BooleanField(
                blank=True,
                help_text="Does the cafe have a prayer room/musala? (null=don't know)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="has_smoking_area",
            field=models.BooleanField(
                blank=True,
                help_text="Does the cafe have a designated smoking area? (null=don't know)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("IDR", "Indonesian Rupiah (Rp)"),
                    ("SGD", "Singapore Dollar (S$)"),
                    ("MYR", "Malaysian Ringgit (RM)"),
                    ("THB", "Thai Baht (฿)"),
                    ("PHP", "Philippine Peso (₱)"),
                    ("VND", "Vietnamese Dong (₫)"),
                    ("JPY", "Japanese Yen (¥)"),
                    ("CNY", "Chinese Yuan (¥)"),
                    ("KRW", "Korean Won (₩)"),
                    ("INR", "Indian Rupee (₹)"),
                    ("AUD", "Australian Dollar (A$)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                ],
                default="USD",
                help_text="Currency code (e.g., USD, IDR, SGD)",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="amount_spent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount spent at the cafe",
                max_digits=10,
                null=True,
            ),
        ),
    ]
