# Generated by Django 5.2.7 on 2025-11-25 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0002_cafeflag"),
        ("reviews", "0005_review_has_prayer_room_review_has_smoking_area_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["cafe", "is_hidden"], name="review_cafe_hidden_idx"
            ),
        ),
    ]
