# Generated by Django 5.2.7 on 2025-11-26 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0004_add_cache_fields"),
        ("reviews", "0006_add_composite_index_review_cafe_hidden"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["cafe", "is_hidden", "-created_at"],
                name="review_cafe_hidden_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["-helpful_count"], name="review_helpful_count_idx"
            ),
        ),
    ]
