# Generated by Django 5.2.7 on 2025-12-30 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0005_remove_postgis_field"),
        ("reviews", "0007_add_composite_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="visit",
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user", "cafe"], name="review_user_cafe_idx"),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "cafe"), name="unique_user_cafe_review"
            ),
        ),
    ]
