# Generated by Django 5.2.7 on 2026-04-08 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_review_visit_review_review_user_cafe_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bathroom_quality',
        ),
        migrations.RemoveField(
            model_name='review',
            name='coffee_quality',
        ),
        migrations.RemoveField(
            model_name='review',
            name='menu_options',
        ),
        migrations.RemoveField(
            model_name='review',
            name='space_availability',
        ),
        migrations.AlterField(
            model_name='review',
            name='visit_time',
            field=models.IntegerField(blank=True, choices=[(1, 'Morning (Open - 1pm)'), (2, 'Afternoon (1pm - 6pm)'), (3, 'Evening (6pm - Close)')], help_text='Time of visit (deprecated, now stored in Visit model)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
