# Generated by Django 5.2.7 on 2026-04-28 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_hidden_review_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='visit_time',
            field=models.IntegerField(blank=True, choices=[(1, 'Morning (Open - 1pm)'), (2, 'Afternoon (1pm - 6pm)'), (3, 'Evening (6pm - Close)')], help_text='Time of visit (1=Morning, 2=Afternoon, 3=Evening)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
