# Generated by Django 5.2.7 on 2026-05-04 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_add_indoor_outdoor_seating_and_fix_facility_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='visit_time',
            field=models.IntegerField(blank=True, choices=[(1, 'Morning (6AM - 12PM)'), (2, 'Afternoon (12PM - 6PM)'), (3, 'Evening (6PM - 12AM)')], help_text='Time of visit (1=Morning, 2=Afternoon, 3=Evening)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
